# Generated by Django 4.2.17 on 2025-01-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='created_at',
        ),
    ]
